plasma:
  image: openfresh/plasma:latest
  ports:
    - 8080:8080
  environment:
    PLASMA_SUBSCRIBER_TYPE: redis
    PLASMA_SUBSCRIBER_REDIS_ADDR: redis:6379
    PLASMA_SUBSCRIBER_REDIS_CHANNELS: plasma
    PLASMA_SUBSCRIBER_REDIS_OVER_MAX_RETRY_BEHAVIOR: alive
    PLASMA_SUBSCRIBER_REDIS_MAX_RETRY: 5
    PLASMA_SUBSCRIBER_REDIS_TIMEOUT: 1s
    PLASMA_SUBSCRIBER_REDIS_RETRY_INTERBAL: 5s
  links:
    - redis
redis:
  image: redis:3.2.8-alpine
  ports:
    - 6379:6379

